import { TExperience } from '../types';
import { Skills } from './skills';

export const workExperienceData: TExperience[] = [
  {
    id: 'nexpando',
    company: {
      name: 'Nexpando',
      url: 'https://nexpando.com/',
      logo: `/experiences/nexpando.png`,
      location: 'Ho Chi Minh City, Vietnam',
      periodFrom: 'Oct 2025',
      isCurrentEmployer: true,
    },
    positions: [
      {
        isExpanded: true,
        id: 'software_engineer_nexpando',
        title: 'Software Engineer',
        periodFrom: 'Oct 2025',
        type: 'Full-time',
        descriptions: [
          `Lead the front end for BANA, a multi-tenant point-of-sale platform for the Vietnam market - five apps in a Bun monorepo (client admin, back office, the Sale terminal, in-table self-ordering and the e-invoice portal) sharing one core package and two design systems.`,
          `Set the client architecture - dependency-injected data and auth providers, a shared core package, and an admin UI kit plus a sale UI kit the apps consume instead of duplicating components.`,
          `Delivered the F&B domain end to end - table service, floor plans, reservations and the kitchen display - spanning the Sale terminal and the admin that configures it.`,
          `Implemented the offline-capable local domain layer in Rust inside the Tauri 2 shell (SQLite via SeaORM), shipping the terminal to desktop, Android, iOS, payment-terminal and browser targets from one React codebase.`,
          `Rebuilt printing as a service layer and hardened the realtime tier - sale order, reservation and kitchen channels with offline detection, reconnect on foreground and silent auth recovery.`,
          `Drove the next-generation terminal's migration from Radix to Base UI, and defined the shared primitives - virtualized form autocompletes, virtual list and grid, adaptive dialog surfaces, PDF viewer - adopted across the monorepo.`,
          `Break down and review the team's work, scoping new apps and handing off delivery while keeping every app on the shared foundation.`,
        ],
        skills: [
          Skills.TYPESCRIPT,
          Skills.REACT_JS,
          Skills.TAURI,
          Skills.RUST,
          Skills.VITE,
          Skills.TAILWIND_CSS,
          Skills.SHADCN_UI,
          Skills.BASE_UI,
          Skills.RADIX_UI,
          Skills.REACT_ADMIN,
          Skills.REDUX_TOOLKIT,
          Skills.TANSTACK_QUERY,
          Skills.TANSTACK_TABLE,
          Skills.TANSTACK_VIRTUAL,
          Skills.REACT_HOOK_FORM,
          Skills.ZOD,
          Skills.WEB_SOCKET,
          Skills.PWA,
        ],
      },
    ],
  },
  {
    id: 'minimal_technology',
    company: {
      name: 'Minimal Technology',
      url: 'https://minimaltek.com',
      logo: `/experiences/minimal_technology.png`,
      location: 'Ho Chi Minh City, Vietnam',
      periodFrom: 'Nov 2022',
      isCurrentEmployer: true,
    },
    positions: [
      {
        id: 'freelance_minimal_technology',
        title: 'Front End Developer',
        periodFrom: 'Sep 2025',
        type: 'Contract',
        descriptions: [
          `Supported ERP systems through ongoing maintenance, bug fixing, and UI/UX improvements, helping clients keep their applications stable and user-friendly.`,
        ],
        skills: [
          Skills.TYPESCRIPT,
          Skills.REACT_JS,
          Skills.MATERIAL_UI,
          Skills.MATERIAL_REACT_TABLE,
          Skills.REACT_ADMIN,
          Skills.TANSTACK_QUERY,
          Skills.TANSTACK_VIRTUAL,
          Skills.REDUX_TOOLKIT,
          Skills.REACT_HOOK_FORM,
          Skills.ZOD,
        ],
      },
      {
        isExpanded: true,
        id: 'fe_minimal_technology',
        title: 'Front End Developer',
        periodFrom: 'Nov 2022',
        periodTo: 'Aug 2025',
        type: 'Full-time',
        descriptions: [
          `Developed and maintained ERP and Trading systems, delivering scalable, high performance applications with real-time data.`,
          `Built custom internal tools to improve efficiency and maintainability.`,
          `Focused on scalable, high-performance, and easy to maintain.`,
          `Collaborated with cross-functional teams to deliver high-impact features on tight deadlines.`,
        ],
        skills: [
          Skills.TYPESCRIPT,
          Skills.REACT_JS,
          Skills.MATERIAL_UI,
          Skills.MATERIAL_REACT_TABLE,
          Skills.REACT_ADMIN,
          Skills.TANSTACK_QUERY,
          Skills.TANSTACK_VIRTUAL,
          Skills.REDUX_TOOLKIT,
          Skills.REDUX_SAGA,
          Skills.REACT_HOOK_FORM,
          Skills.ZOD,
          Skills.FIREBASE,
          Skills.REACT_KONVA,
          Skills.ELECTRON_JS,
          Skills.ELECTRON_UPDATER,
          Skills.RXJS,
          Skills.SOCKET_IO,
          Skills.WEB_SOCKET,
          Skills.LIGHTWEIGHT_CHARTS,
        ],
      },
    ],
  },
];
