import { IProject } from '../types';
import { Skills } from './skills';

export const projectData: IProject[] = [
  {
    id: 'bana-self-order',
    title: 'BANA - Self Order',
    periodFrom: 'Aug 2026',
    description:
      'In-table self-ordering for F&B: the guest scans the QR code on the table and orders, calls staff or asks for the bill from their own phone. Browser-only, nothing to install.',
    role: 'Software Engineer.',
    responsibilities: [
      `Owned the architecture and scoped the delivery, bootstrapping the app as a browser-only sibling of Sale - same dependency-injection container, data and auth providers, i18n, store and theming - with the native shell, desktop IPC and printing stack removed.`,
      `Directed the guest ordering flow the team built out: QR-bound guest sessions on the sale-channel API, a cart batched into sale orders, and staff-call and bill requests pushed back to the terminal.`,
      `Standardised the app on the shared <b>sale UI kit</b>, keeping the guest surface visually consistent with the terminal it orders through and on a single component upgrade path.`,
      `Set the mobile interaction model - bottom navigation, pull-to-refresh, drawer-based product editing and a virtualized catalog - on primitives already proven in Sale.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.VITE,
      Skills.TAILWIND_CSS,
      Skills.SHADCN_UI,
      Skills.BASE_UI,
      Skills.REDUX_TOOLKIT,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.REACT_HOOK_FORM,
      Skills.ZOD,
    ],
    logo: `/projects/bana/logo.svg`,
    logoDark: `/projects/bana/logo-dark.svg`,
  },
  {
    id: 'bana-e-invoice',
    title: 'BANA - E-Invoice Portal',
    periodFrom: 'Aug 2026',
    description:
      'A public, no-auth page where a buyer who just paid at the POS claims their own VAT e-invoice from the link on the receipt.',
    role: 'Software Engineer.',
    responsibilities: [
      `Scoped the app and handed off delivery: a single no-auth claim screen forked from the admin stack and cut back to a REST-only endpoint layer, with offline handling and localized error surfaces.`,
      `Wired the app into the deployment stack and its environment configuration.`,
      `Resolved platform-wide defects that surfaced here first - deduplicated the dependency-injection packages so the injectable container resolved in production builds, and gave error toasts a stable id so they stop stacking.`,
      `Rebuilt the favicon set and drew the shared wordmark into the header and splash, aligning branding across every app and letting each tab icon follow its own app's theme.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.VITE,
      Skills.TAILWIND_CSS,
      Skills.REACT_ADMIN,
      Skills.TANSTACK_QUERY,
      Skills.REACT_HOOK_FORM,
      Skills.ZOD,
      Skills.PWA,
    ],
    logo: `/projects/bana/logo.svg`,
    logoDark: `/projects/bana/logo-dark.svg`,
  },
  {
    id: 'bana-bo',
    title: 'BANA - Back Office',
    periodFrom: 'Feb 2026',
    description:
      'The operations-facing back office: org-wide configuration plus a per-merchant administration tier, and the widest feature surface on the platform.',
    role: 'Software Engineer.',
    responsibilities: [
      `Extended the org-wide and per-merchant administration tiers - ledger, sale channels, merchant settings - keeping the domain model in step with Client Admin as it evolved.`,
      `Consolidated the virtualized autocomplete, data-table and form primitives into a shared <b>admin UI kit</b>, so both admin apps ship from one implementation instead of diverging copies.`,
      `Hardened the realtime tier: a socket status indicator, offline detection, reconnect on foreground and silent auth recovery, surfacing connection health to operators.`,
      `Implemented the theme-switch <b>View Transition</b> animation and the per-user locale sync shared by both admin apps.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.VITE,
      Skills.TAILWIND_CSS,
      Skills.REACT_ADMIN,
      Skills.REDUX_TOOLKIT,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_TABLE,
      Skills.TANSTACK_VIRTUAL,
      Skills.REACT_HOOK_FORM,
      Skills.ZOD,
      Skills.WEB_SOCKET,
      Skills.PWA,
    ],
    logo: `/projects/bana/logo.svg`,
    logoDark: `/projects/bana/logo-dark.svg`,
  },
  {
    id: 'bana-sale',
    title: 'BANA - Sale',
    periodFrom: 'Dec 2025',
    description:
      'The merchant point-of-sale client: one React codebase shipped as a Tauri 2 desktop app, an Android and iOS build, a dedicated payment-terminal target and a browser build - offline capable, with a desktop and a mobile UI picked at runtime and screens routed by merchant industry.',
    role: 'Software Engineer.',
    responsibilities: [
      `Led the terminal across two generations - shipped v1, then set the architecture for v2 and drove its migration from Radix to <b>Base UI</b> behind a shared <b>sale UI kit</b>.`,
      `Built the sales surfaces - <b>Table Service</b>, <b>Quick Sale</b>, Retail Sale and the Order Checkout payment stepper - each split into a separate desktop and mobile body behind one route, with split order, move table, barcode checkout and hotkey quick actions.`,
      `Implemented the offline-capable local domain layer in <b>Rust</b> inside the Tauri shell - sale order, restaurant, inventory stock and tax entities on SQLite through SeaORM - so a terminal keeps selling when the network drops.`,
      `Built the <b>Reservation</b> module - list, drafted create/edit form, table grid, canvas map and calendar - and split its state out of the restaurant slice.`,
      `Rebuilt <b>printing as a service layer</b>, moving receipt, shift-report and kitchen-ticket output off the screens and behind one interface, and drove the <b>Kitchen Display</b> board on its own socket channel.`,
      `Established the shared primitives the team builds on: <b>VirtualList</b> and <b>VirtualGridList</b>, and adaptive dialog, popover and sheet surfaces that swap presentation between desktop and mobile.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.TAURI,
      Skills.RUST,
      Skills.VITE,
      Skills.TAILWIND_CSS,
      Skills.SHADCN_UI,
      Skills.BASE_UI,
      Skills.RADIX_UI,
      Skills.REDUX_TOOLKIT,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.REACT_HOOK_FORM,
      Skills.ZOD,
      Skills.WEB_SOCKET,
      Skills.SOCKET_IO,
    ],
    logo: `/projects/bana/logo.svg`,
    logoDark: `/projects/bana/logo-dark.svg`,
  },
  {
    id: 'bana-client',
    title: 'BANA - Client Admin',
    periodFrom: 'Nov 2025',
    description:
      'The admin workspace where merchant owners and managers run a store: product catalog, sales, inventory, procurement, finance and reporting.',
    role: 'Software Engineer.',
    responsibilities: [
      `Owned the front-end foundation of the admin tier: split shared logic into a <b>core</b> package and built the <b>admin UI kit</b> - application shell, draggable sidebar, color theming, data table with column ordering and inline edit cells, notifications - that both admin apps stand on.`,
      `Designed <b>RHFVirtualAutocomplete</b> / <b>RHFVirtualAutocompleteArray</b>, form-bound selects pairing TanStack Virtual windowing with paginated fetching, and rolled them out as the single combobox primitive across both admin apps.`,
      `Built the <b>procurement</b> surface end to end - requisition tickets, purchase orders, goods receipt and print templates - on the shared inventory-ticket model.`,
      `Built the <b>F&B floor-plan</b> authoring flow - rooms, floors and tables on a zoomable canvas - that the Sale terminals consume at runtime.`,
      `Wired <b>WebSocket</b> subscriptions into the Sale Order and Transaction screens so the admin reconciles terminal activity without a refresh, and added error boundaries, offline handling and per-organizer theming across the app.`,
      `Delivered merchant and organizer onboarding, product and variant management, sale customers and the ledger surface.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.VITE,
      Skills.TAILWIND_CSS,
      Skills.REACT_ADMIN,
      Skills.REDUX_TOOLKIT,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_TABLE,
      Skills.TANSTACK_VIRTUAL,
      Skills.REACT_HOOK_FORM,
      Skills.ZOD,
      Skills.WEB_SOCKET,
      Skills.PWA,
    ],
    logo: `/projects/bana/logo.svg`,
    logoDark: `/projects/bana/logo-dark.svg`,
  },
  {
    id: 'cts-web',
    title: 'Crypto Trading System - Web App',
    periodFrom: 'Jul 2025',
    periodTo: 'Aug 2025',
    description:
      'Progressive Web App version of the desktop trading system, designed as a mobile app for internal traders.',
    role: 'Front End Developer.',
    responsibilities: [
      `Adapted the architecture of Crypto Trading System - Desktop Trading, reusing core solutions while customizing logic for project needs.`,
      `Implemented a subscription manager to handle socket connections for low-latency streaming of market and account data.`,
      `Implemented Order Book table by updating DOM elements directly via RxJS, reducing CPU usage by <b>85-90%</b>.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.REDUX_TOOLKIT,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.RXJS,
      Skills.SOCKET_IO,
    ],
    logo: `/projects/cts-web/logo.png`,
    images: [
      {
        id: 'cts-web-1',
        src: `/projects/cts-web/login_screen.png`,
        alt: `Login Screen`,
      },
      {
        id: 'cts-web-2',
        src: `/projects/cts-web/home_screen.png`,
        alt: `Home Screen`,
      },
      {
        id: 'cts-web-3',
        src: `/projects/cts-web/order_book_screen.png`,
        alt: `Order Book Screen`,
      },
      {
        id: 'cts-web-4',
        src: `/projects/cts-web/order_history_screen.png`,
        alt: `Order History Screen`,
      },
      {
        id: 'cts-web-5',
        src: `/projects/cts-web/portfolio_screen.png`,
        alt: `Portfolio Screen`,
      },
    ],
  },
  {
    id: 'cts-dt',
    title: 'Crypto Trading System - Desktop Trading',
    periodFrom: 'Jan 2025',
    periodTo: 'Aug 2025',
    description: 'A high-performance trading desktop application for internal traders.',
    role: 'Front End Developer.',
    responsibilities: [
      `Improved market data rendering with Redux Toolkit, RxJS and component splitting, lowering CPU usage by <b>70-80%</b>.`,
      `Enhanced order history rendering with batch updates, cutting CPU usage by <b>80-90%</b>.`,
      `Developed a <b>TradingView-inspired Order Chart</b> with custom indicators and plugins on Lightweight Charts, including Min/Max Price markers, Floating Order Form, Context Menu, Order History, Open Orders with drag-and-drop, and Portfolio management with real-time PnL%.`,
      `Built an interactive Order Book table with click and drag-and-drop actions, enabling traders to execute, modify, and cancel orders seamlessly.`,
      `Automated cross-platform app updates with Electron Updater with Github Release; built CI/CD pipelines with Github Actions for publishing apps.`,
      `Built <b>workspace feature</b> allowing traders to set up multiple windows layout and automatically saves window states for seamless session recovery.`,
    ],
    skills: [
      Skills.ELECTRON_JS,
      Skills.ELECTRON_UPDATER,
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.LIGHTWEIGHT_CHARTS,
      Skills.REDUX_TOOLKIT,
      Skills.REDUX_SAGA,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.RXJS,
      Skills.SOCKET_IO,
      Skills.WEB_SOCKET,
    ],
    logo: `/projects/cts-dt/logo.png`,
    images: [
      {
        id: 'cts-dt-1',
        src: `/projects/cts-dt/login_screen.png`,
        alt: `Login Screen`,
      },
      {
        id: 'cts-dt-2',
        src: `/projects/cts-dt/0000_home_screen.png`,
        alt: `Home Screen`,
      },
      {
        id: 'cts-dt-3',
        src: `/projects/cts-dt/0001_account_balance_screen.png`,
        alt: `Account Balance Screen`,
      },
      {
        id: 'cts-dt-4',
        src: `/projects/cts-dt/0002_market_watch_screen.png`,
        alt: `Market Watch Screen`,
      },
      {
        id: 'cts-dt-5',
        src: `/projects/cts-dt/1000_all_screen.png`,
        alt: `All Screen`,
      },
      {
        id: 'cts-dt-6',
        src: `/projects/cts-dt/1001_order_book_screen.png`,
        alt: `Order Book Screen`,
      },
      {
        id: 'cts-dt-7',
        src: `/projects/cts-dt/1003_market_trade_screen.png`,
        alt: `Market Trade Screen`,
      },
      {
        id: 'cts-dt-8',
        src: `/projects/cts-dt/1004_portfolio_screen.png`,
        alt: `Portfolio Screen`,
      },
      {
        id: 'cts-dt-9',
        src: `/projects/cts-dt/1006_order_history_screen.png`,
        alt: `Order History Screen`,
      },
      {
        id: 'cts-dt-10',
        src: `/projects/cts-dt/1007_hedge_order_screen.png`,
        alt: `Hedge Order Screen`,
      },
      {
        id: 'cts-dt-11',
        src: `/projects/cts-dt/2000_order_chart_screen.png`,
        alt: `Order Chart Screen`,
      },
      {
        id: 'cts-dt-12',
        src: `/projects/cts-dt/2001_chart_multiple_panel_screen.png`,
        alt: `Chart Multiple Panel Screen`,
      },
      {
        id: 'cts-dt-13',
        src: `/projects/cts-dt/2002_tick_chart_screen.png`,
        alt: `Tick Chart Screen`,
      },
      {
        id: 'cts-dt-14',
        src: `/projects/cts-dt/2003_chart_sync_screen.png`,
        alt: `Chart Sync Screen`,
      },
    ],
    isExpanded: true,
  },
  {
    id: 'sm-studio',
    title: 'Studio Samick',
    periodFrom: 'Oct 2023',
    periodTo: 'Dec 2024',
    description: 'ERP System for Samick Studio.',
    role: 'Front End Developer.',
    responsibilities: [
      `Adapted and extended the architecture of Samick Furniture ERP System, reusing core solutions  while customizing business logic for project needs.`,
      `Implemented multi-row selection and advanced column filtering in tables, improving user workflow efficiency.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.MATERIAL_REACT_TABLE,
      Skills.REDUX_TOOLKIT,
      Skills.REACT_QUERY,
      Skills.TANSTACK_VIRTUAL,
    ],
    logo: `/projects/sm-studio/logo.png`,
    images: [
      {
        id: 'sm-erp-1',
        src: `/projects/sm-studio/login_screen.png`,
        alt: `Login Screen`,
      },
    ],
  },
  {
    id: 'sm-erp',
    title: 'Samick Furniture ERP System',
    periodFrom: 'Nov 2022',
    periodTo: 'Dec 2024',
    description:
      'Samick ERP is an integrated platform business management covering operations, logistics, sales, human resources, and customer services.',
    role: 'Front End Developer.',
    responsibilities: [
      `Optimized large dataset rendering using TanStack Virtual and infinite scrolling, improving load time and overall user experience.`,
      `Enhanced form handling with React Hook Form and Zod validation, reducing rendering overhead and preventing invalid submissions.`,
      `Integrated Firebase push notifications and Socket.io for real-time UI updates.`,
      `Delivered PWA modules and applied code splitting and lazy loading to boost loading performance.`,
      `Built drawing tools with React Konva, enabling users to annotate product images directly.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.MATERIAL_REACT_TABLE,
      Skills.REACT_HOOK_FORM,
      Skills.ZOD,
      Skills.REDUX_TOOLKIT,
      Skills.REDUX_SAGA,
      Skills.REACT_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.RXJS,
      Skills.FIREBASE,
      Skills.SOCKET_IO,
      Skills.REACT_KONVA,
    ],
    logo: `/projects/sm-erp/logo.png`,
    images: [
      {
        id: 'sm-erp-1',
        src: `/projects/sm-erp/login_screen.png`,
        alt: `Login Screen`,
      },
    ],
  },
];
