import { IProject } from '../types';
import { Skills } from './skills';

// --------------------------------------------------
export const projectData: IProject[] = [
  {
    id: 'cts-web',
    title: 'Crypto Trading System - Web App',
    periodFrom: 'Jul 2025',
    periodTo: 'Aug 2025',
    description:
      'Progressive Web App version of the desktop trading system, designed as a mobile app for internal traders.',
    role: 'Front End Developer.',
    responsibilities: [
      `Adapted the architecture of Crypto Trading System - Desktop Trading, reusing core solutions while customizing logic for project needs.`,
      `Implemented a subscription manager to handle socket connections for low-latency streaming of market and account data.`,
      `Implemented Order Book table by updating DOM elements directly via RxJS, reducing CPU usage by <b>85-90%</b>.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.REDUX_TOOLKIT,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.RXJS,
      Skills.SOCKET_IO,
    ],
    logo: `/projects/cts-web/logo.png`,
    images: [
      {
        id: 'cts-web-1',
        src: `/projects/cts-web/login_screen.png`,
        alt: `Login Screen`,
      },
      {
        id: 'cts-web-2',
        src: `/projects/cts-web/home_screen.png`,
        alt: `Home Screen`,
      },
      {
        id: 'cts-web-3',
        src: `/projects/cts-web/order_book_screen.png`,
        alt: `Order Book Screen`,
      },
      {
        id: 'cts-web-4',
        src: `/projects/cts-web/order_history_screen.png`,
        alt: `Order History Screen`,
      },
      {
        id: 'cts-web-5',
        src: `/projects/cts-web/portfolio_screen.png`,
        alt: `Portfolio Screen`,
      },
    ],
  },
  {
    id: 'cts-dt',
    title: 'Crypto Trading System - Desktop Trading',
    periodFrom: 'Jan 2025',
    periodTo: 'Aug 2025',
    description: 'A high-performance trading desktop application for internal traders.',
    role: 'Front End Developer.',
    responsibilities: [
      `Improved market data rendering with Redux Toolkit, RxJS and component splitting, lowering CPU usage by <b>70-80%</b>.`,
      `Enhanced order history rendering with batch updates, cutting CPU usage by <b>80-90%</b>.`,
      `Developed a <b>TradingView-inspired Order Chart</b> with custom indicators and plugins on Lightweight Charts, including Min/Max Price markers, Floating Order Form, Context Menu, Order History, Open Orders with drag-and-drop, and Portfolio management with real-time PnL%.`,
      `Built an interactive Order Book table with click and drag-and-drop actions, enabling traders to execute, modify, and cancel orders seamlessly.`,
      `Automated cross-platform app updates with Electron Updater with Github Release; built CI/CD pipelines with Github Actions for publishing apps.`,
      `Built <b>workspace feature</b> allowing traders to set up multiple windows layout and automatically saves window states for seamless session recovery.`,
    ],
    skills: [
      Skills.ELECTRON_JS,
      Skills.ELECTRON_UPDATER,
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.LIGHTWEIGHT_CHARTS,
      Skills.REDUX_TOOLKIT,
      Skills.REDUX_SAGA,
      Skills.TANSTACK_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.RXJS,
      Skills.SOCKET_IO,
      Skills.WEB_SOCKET,
    ],
    logo: `/projects/cts-dt/logo.png`,
    images: [
      {
        id: 'cts-dt-1',
        src: `/projects/cts-dt/login_screen.png`,
        alt: `Login Screen`,
      },
      {
        id: 'cts-dt-2',
        src: `/projects/cts-dt/0000_home_screen.png`,
        alt: `Home Screen`,
      },
      {
        id: 'cts-dt-3',
        src: `/projects/cts-dt/0001_account_balance_screen.png`,
        alt: `Account Balance Screen`,
      },
      {
        id: 'cts-dt-4',
        src: `/projects/cts-dt/0002_market_watch_screen.png`,
        alt: `Market Watch Screen`,
      },
      {
        id: 'cts-dt-5',
        src: `/projects/cts-dt/1000_all_screen.png`,
        alt: `All Screen`,
      },
      {
        id: 'cts-dt-6',
        src: `/projects/cts-dt/1001_order_book_screen.png`,
        alt: `Order Book Screen`,
      },
      {
        id: 'cts-dt-7',
        src: `/projects/cts-dt/1003_market_trade_screen.png`,
        alt: `Market Trade Screen`,
      },
      {
        id: 'cts-dt-8',
        src: `/projects/cts-dt/1004_portfolio_screen.png`,
        alt: `Portfolio Screen`,
      },
      {
        id: 'cts-dt-9',
        src: `/projects/cts-dt/1006_order_history_screen.png`,
        alt: `Order History Screen`,
      },
      {
        id: 'cts-dt-10',
        src: `/projects/cts-dt/1007_hedge_order_screen.png`,
        alt: `Hedge Order Screen`,
      },
      {
        id: 'cts-dt-11',
        src: `/projects/cts-dt/2000_order_chart_screen.png`,
        alt: `Order Chart Screen`,
      },
      {
        id: 'cts-dt-12',
        src: `/projects/cts-dt/2001_chart_multiple_panel_screen.png`,
        alt: `Chart Multiple Panel Screen`,
      },
      {
        id: 'cts-dt-13',
        src: `/projects/cts-dt/2002_tick_chart_screen.png`,
        alt: `Tick Chart Screen`,
      },
      {
        id: 'cts-dt-14',
        src: `/projects/cts-dt/2003_chart_sync_screen.png`,
        alt: `Chart Sync Screen`,
      },
    ],
    isExpanded: true,
  },
  {
    id: 'sm-studio',
    title: 'Studio Samick',
    periodFrom: 'Oct 2023',
    periodTo: 'Dec 2024',
    description: 'ERP System for Samick Studio.',
    role: 'Front End Developer.',
    responsibilities: [
      `Adapted and extended the architecture of Samick Furniture ERP System, reusing core solutions  while customizing business logic for project needs.`,
      `Implemented multi-row selection and advanced column filtering in tables, improving user workflow efficiency.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.MATERIAL_REACT_TABLE,
      Skills.REDUX_TOOLKIT,
      Skills.REACT_QUERY,
      Skills.TANSTACK_VIRTUAL,
    ],
    logo: `/projects/sm-studio/logo.png`,
    images: [
      {
        id: 'sm-erp-1',
        src: `/projects/sm-studio/login_screen.png`,
        alt: `Login Screen`,
      },
    ],
  },
  {
    id: 'sm-erp',
    title: 'Samick Furniture ERP System',
    periodFrom: 'Nov 2022',
    periodTo: 'Dec 2024',
    description:
      'Samick ERP is an integrated platform business management covering operations, logistics, sales, human resources, and customer services.',
    role: 'Front End Developer.',
    responsibilities: [
      `Optimized large dataset rendering using TanStack Virtual and infinite scrolling, improving load time and overall user experience.`,
      `Enhanced form handling with React Hook Form and Zod validation, reducing rendering overhead and preventing invalid submissions.`,
      `Integrated Firebase push notifications and Socket.io for real-time UI updates.`,
      `Delivered PWA modules and applied code splitting and lazy loading to boost loading performance.`,
      `Built drawing tools with React Konva, enabling users to annotate product images directly.`,
    ],
    skills: [
      Skills.REACT_JS,
      Skills.TYPESCRIPT,
      Skills.REACT_ADMIN,
      Skills.MATERIAL_UI,
      Skills.MATERIAL_REACT_TABLE,
      Skills.REACT_HOOK_FORM,
      Skills.ZOD,
      Skills.REDUX_TOOLKIT,
      Skills.REDUX_SAGA,
      Skills.REACT_QUERY,
      Skills.TANSTACK_VIRTUAL,
      Skills.RXJS,
      Skills.FIREBASE,
      Skills.SOCKET_IO,
      Skills.REACT_KONVA,
    ],
    logo: `/projects/sm-erp/logo.png`,
    images: [
      {
        id: 'sm-erp-1',
        src: `/projects/sm-erp/login_screen.png`,
        alt: `Login Screen`,
      },
    ],
  },
];
